### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ionutindreica** [getbase/starter#1]
Hi I have used your step by step tutorial on how to start using base but I've encountered this error when use npm start command. Do you know what could generate this?
Here is the error I'm getting in the console.

C:\Users\John\Dropbox\web-content\www\amzhu2>npm start

> @ start C:\Users\John\Dropbox\web-content\www\amzhu2
> gulp

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\John\Dropbox\web-content\www\amzhu2\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\John\Dropbox\web-content\www\amzhu2\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\John\Dropbox\web-content\www\amzhu2\gulpfile.js:91:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John\AppData\Roaming\npm-cache\_logs\2018-11-07T07_24_41_133Z-debug.log

**Comment by matthewhartman** [comment]
Hey @ionutindreica 

Apologies for the late reply. I have replaced GulpJS with Webpack so it all should be working as normal now.

Can you please pull the latest version (4.1.0) and do a fresh `npm install`

Cheers John :+1:
